# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collecteddata',
            old_name='statistic_data',
            new_name='fund',
        ),
    ]
